name: API
on:
  push:
jobs:
  Prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: KristianFJones/npm-run-action@alternative
        with:
          scriptName: 'prettier'
          scriptPath: 'API/'
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: KristianFJones/npm-run-action@alternative
        with:
          scriptName: 'lint'
          scriptPath: 'API/'
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [Prettier, Lint]
    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: API/Dockerfile
          name: docker.pkg.github.com/kristianfjones/backup-management/backup-management-api
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: API
