name: Client Builds
on:
  push:
jobs:
  BuildClientDL:
    name: Build ClientDL
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: ClientDL/Dockerfile
          name: docker.pkg.github.com/kristianfjones/backup-management/backup-management-clientdl
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: ClientDL
          cache: true
  BuildClientBCKUP:
    name: Build ClientBCKUP
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: ClientBCKUP/Dockerfile
          name: docker.pkg.github.com/kristianfjones/backup-management/backup-management-clientbckup
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: ClientBCKUP
          cache: true
